// <auto-generated />
using E_commerce_23TH0024.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce_23TH0024.Data.Migrations.SystemSetting
{
    [DbContext(typeof(SystemSettingDbContext))]
    partial class SystemSettingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerce_23TH0024.Models.SystemSetting.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConfigType")
                        .HasColumnType("int");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configuration", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.SystemSetting.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdNhomMenu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiMenu")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiMenu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNhomMenu");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.SystemSetting.NhomMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNhomMenu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NhomMenu", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.SystemSetting.Menu", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.SystemSetting.NhomMenu", "NhomMenu")
                        .WithMany("Menus")
                        .HasForeignKey("IdNhomMenu");

                    b.Navigation("NhomMenu");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.SystemSetting.NhomMenu", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
