// <auto-generated />
using System;
using E_commerce_23TH0024.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce_23TH0024.Data.Migrations.Order
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20250712181026_UpdateOrderSchema")]
    partial class UpdateOrderSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDonHang")
                        .HasColumnType("int");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDonHang");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.CustomerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTypes", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.DeliveryMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeliveryTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMethods", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.DiscountRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("Discount_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCustomerType")
                        .HasColumnType("int");

                    b.Property<int?>("IdLoaiSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("MinTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomerType");

                    b.ToTable("DiscountRules", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiscountRuleId")
                        .HasColumnType("int");

                    b.Property<int?>("IdDeliveryMethod")
                        .HasColumnType("int");

                    b.Property<int?>("IdDiscountRule")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVienDuyet")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVienGiao")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalProductAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountRuleId");

                    b.HasIndex("IdDeliveryMethod");

                    b.HasIndex("KhachHangId");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdAspNetUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<int?>("IdCustomerType")
                        .HasColumnType("int");

                    b.Property<int?>("IdDistrict")
                        .HasColumnType("int");

                    b.Property<int?>("IdWard")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomerType");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GatewayTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDonHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDonHang");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.ShippingRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FixedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("FromDistance")
                        .HasColumnType("float");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<int?>("IdDeliveryMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("ToDistance")
                        .HasColumnType("float");

                    b.Property<decimal?>("WeightLitmit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdDeliveryMethod");

                    b.ToTable("ShippingRates", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.ChiTietDonHang", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Order.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IdDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.DiscountRule", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Order.CustomerType", "CustomerType")
                        .WithMany("DiscountRules")
                        .HasForeignKey("IdCustomerType");

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.DonHang", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Order.DiscountRule", "DiscountRule")
                        .WithMany()
                        .HasForeignKey("DiscountRuleId");

                    b.HasOne("E_commerce_23TH0024.Models.Order.DeliveryMethod", "DeliveryMethod")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdDeliveryMethod");

                    b.HasOne("E_commerce_23TH0024.Models.Order.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId");

                    b.Navigation("DeliveryMethod");

                    b.Navigation("DiscountRule");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.KhachHang", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Order.CustomerType", "CustomerType")
                        .WithMany("KhachHangs")
                        .HasForeignKey("IdCustomerType");

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.Payment", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Order.DonHang", "DonHang")
                        .WithMany("Payments")
                        .HasForeignKey("IdDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.ShippingRate", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Order.DeliveryMethod", "DeliveryMethod")
                        .WithMany("ShippingRates")
                        .HasForeignKey("IdDeliveryMethod");

                    b.Navigation("DeliveryMethod");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.CustomerType", b =>
                {
                    b.Navigation("DiscountRules");

                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.DeliveryMethod", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("ShippingRates");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Order.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
