// <auto-generated />
using E_commerce_23TH0024.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce_23TH0024.Data.Migrations.Location
{
    [DbContext(typeof(LocationDbContext))]
    partial class LocationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerce_23TH0024.Models.Location.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Location.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCity");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Location.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdDistrict")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdDistrict");

                    b.ToTable("Wards", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Location.District", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Location.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("IdCity");

                    b.Navigation("City");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Location.Ward", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Location.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("IdDistrict");

                    b.Navigation("District");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Location.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Location.District", b =>
                {
                    b.Navigation("Wards");
                });
#pragma warning restore 612, 618
        }
    }
}
