// <auto-generated />
using E_commerce_23TH0024.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce_23TH0024.Data.Migrations.Ecommerce
{
    [DbContext(typeof(EcommerceDbContext))]
    partial class EcommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.AttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdProductAttribute")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProductAttribute");

                    b.ToTable("AttributeValues", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.ProductAttribute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttributeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductAttributes", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPham");

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.ProductVariantAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdAttributeValue")
                        .HasColumnType("int");

                    b.Property<string>("IdProductAttribute")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("IdProductVariant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAttributeValue");

                    b.HasIndex("IdProductAttribute");

                    b.HasIndex("IdProductVariant");

                    b.ToTable("ProductVariantAttributes", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdLoaiSanPham")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdLoaiSanPham");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.AttributeValue", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Ecommerce.ProductAttribute", "ProductAttribute")
                        .WithMany("AttributeValues")
                        .HasForeignKey("IdProductAttribute");

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.ProductVariant", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Ecommerce.SanPham", "SanPham")
                        .WithMany("ProductVariants")
                        .HasForeignKey("IdSanPham");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.ProductVariantAttribute", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Ecommerce.AttributeValue", "AttributeValue")
                        .WithMany("ProductVariantAttributes")
                        .HasForeignKey("IdAttributeValue");

                    b.HasOne("E_commerce_23TH0024.Models.Ecommerce.ProductAttribute", "ProductAttribute")
                        .WithMany("ProductVariantAttributes")
                        .HasForeignKey("IdProductAttribute");

                    b.HasOne("E_commerce_23TH0024.Models.Ecommerce.ProductVariant", "ProductVariant")
                        .WithMany("ProductVariantAttributes")
                        .HasForeignKey("IdProductVariant");

                    b.Navigation("AttributeValue");

                    b.Navigation("ProductAttribute");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.SanPham", b =>
                {
                    b.HasOne("E_commerce_23TH0024.Models.Ecommerce.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdLoaiSanPham");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.AttributeValue", b =>
                {
                    b.Navigation("ProductVariantAttributes");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.ProductAttribute", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("ProductVariantAttributes");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.ProductVariant", b =>
                {
                    b.Navigation("ProductVariantAttributes");
                });

            modelBuilder.Entity("E_commerce_23TH0024.Models.Ecommerce.SanPham", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
